### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-ggar#1]
[EntrevistaTrabajoFinal.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-ggar/files/9465589/EntrevistaTrabajoFinal.pdf)

**Comment by Elisahadad** [comment]
19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
